spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: edu.sw.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001-config.com
    prefer-ip-address: true

info:
  app.name: mircoservicecloud-provider-dept-8001
  comany.name: edu.sw.springcloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
     min-idle: 5
     initial-size: 5
     max-total: 5
     max-wait-millis: 200 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: edu.sw.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001-config.com
    prefer-ip-address: true

info:
  app.name: mircoservicecloud-provider-dept-8001
  comany.name: edu.sw.springcloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

